### Send POST request with json body
POST localhost:8080/api/failures-v2
Content-Type: application/json

{
  "firmaId": 5,
  "prodstufeId": 50,
  "paNrId": 70000,
  "buendelBc": "bc",
  "personalQc": 100,
  "personalQc2": 0,
  "pruefung2": false,
  "abfallId": "101",
  "personalId": 0,
  "schichtplangruppeId": 0,
  "mengeAbfall": 1.0,
  "stueckNr": 0,
  "stueckTeilung": 0,
  "mengeGutz": 0.0,
  "zuschnittFertig": false,
  "mengeGutp": 0.0,
  "pruefungFertig": false
}

#### List all failures
GET localhost:8080/api/failuresv2

#### List summarized top failures for a specific workorder
GET localhost:8080/api/erp/api/failuresv2/top?firmaId=5&prodstufeId=50&paNrID=70000&withStueckNr=false

### List summarized failures detected (in the last hours defined in query) by specified quality controller person
GET localhost:8080/api/failuresv2?hours=48&personalId=100

### List failures entered by workorder and identitfier barcode
GET localhost:8080/api/failuresv2?firmaId=5&prodstufeId=50&paNrId=70000&buendelBc=bc